app:
  github:
    url: https://api.github.com
    token: ${GITHUB_TOKEN}
  stackoverflow:
    url: https://api.stackexchange.com/2.3
    key: ${SO_TOKEN_KEY}
  bot-url: http://localhost:8080

logging:
  level:
    root: INFO

spring:
  # Костыль, который позволяет запускать одновременно ApiUsageScenarioTest и ClientTest.
  main:
    allow-bean-definition-overriding: true
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
